paket.dependencies: pin paket version
We were getting the error:
```
Download of Microsoft.Extensions.DependencyInjection 5.0.1 done in 154 milliseconds. (9655 kbit/s, 0 MB)
Starting task 'DotNet:version': running dotnet --version
6.0.417
Finished (Success) 'DotNet:version' in 00:00:00.9880854
Script is not valid:
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (7,5)-(7,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (8,5)-(8,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (9,5)-(9,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (10,5)-(10,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (11,5)-(11,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (12,5)-(12,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (13,5)-(13,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (14,5)-(14,9): Error FS0039: The namespace or module 'Fake' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (19,0)-(19,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (41,8)-(41,21): Error FS0039: The value, namespace, type or module 'CreateProcess' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (42,11)-(42,24): Error FS0039: The value, namespace, type or module 'CreateProcess' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (44,17)-(44,30): Error FS0039: The value, namespace, type or module 'CreateProcess' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (45,7)-(45,11): Error FS0039: The value, namespace, type or module 'Proc' is not defined. Maybe you want one of the following:
	   proc
	   project
	   Progress
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (49,28)-(49,38): Error FS0039: The type 'Environment' does not define the field, constructor or member 'environVar'.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (66,16)-(66,25): Error FS0039: The value, namespace, type or module 'Changelog' is not defined. Maybe you want one of the following:
	   changelogFilename
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (77,11)-(77,31): Error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (80,8)-(80,42): Error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (82,22)-(82,56): Error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (82,60)-(82,66): Error FS0039: The value, namespace, type or module 'SemVer' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (84,28)-(84,33): Error FS0039: The record label 'Patch' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (91,12)-(91,25): Error FS0039: The value, namespace, type or module 'CreateProcess' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (98,15)-(98,28): Error FS0039: The value, namespace, type or module 'CreateProcess' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (99,15)-(99,28): Error FS0039: The value, namespace, type or module 'CreateProcess' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (100,15)-(100,19): Error FS0039: The value, namespace, type or module 'Proc' is not defined. Maybe you want one of the following:
	   project
	   Progress
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (101,8)-(101,37): Error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (113,0)-(113,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (117,0)-(117,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (121,30)-(121,36): Error FS0039: The namespace or module 'DotNet' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (121,61)-(121,67): Error FS0039: The record label 'Filter' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (123,0)-(123,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (130,0)-(130,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (138,0)-(138,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (151,0)-(151,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (170,0)-(170,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (211,0)-(211,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (227,0)-(227,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (228,0)-(228,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (231,2)-(231,5): Error FS0043: The type 'string' does not support the operator '==>'
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (236,1)-(236,4): Error FS0043: The type 'string' does not support the operator '==>'
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (240,2)-(240,5): Error FS0043: The type 'string' does not support the operator '==>'
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (244,0)-(244,6): Error FS0039: The value, namespace, type or module 'Target' is not defined.
Hint: If you have updated your dependencies you might need to run 'paket install' or delete '/home/runner/work/FSharpLint/FSharpLint/build.fsx.lock' for fake to pick them up.
Hint: If this doesn't help but you are sure this should work try to clean your nuget cache and delete the .fake directory. If this helps please report this problem to Paket.
Hint: Operators now need to be opened manually, try to add 'open Fake.IO.FileSystemOperators' and 'open Fake.IO.Globbing.Operators' to your script to import the most common operators
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 7.1.5' at the top of your dependencies file (/home/runner/work/FSharpLint/FSharpLint/paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
```