Core.Tests(CycloComplexity): fix indentation warning(error)
Somehow when upgrading to .NET6.0 this warning was popping up
(reported as error, so was breaking the build):

Error: /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.Core.Tests/Rules/Conventions/CyclomaticComplexity.fs(233,3): error FS0058: Possible incorrect indentation: this token is offside of
context started at position (230:9). Try indenting this token further or using standard formatting conventions.
[/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.Core.Tests/FSharpLint.Core.Tests.fsproj]
Error: /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.Core.Tests/Rules/Conventions/CyclomaticComplexity.fs(233,3): error FS0058: Possible incorrect indentation: this token is offside of
context started at position (230:9). Try indenting this token further or using standard formatting conventions.
[/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.Core.Tests/FSharpLint.Core.Tests.fsproj]
    0 Warning(s)
    2 Error(s)